name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  datafusion_producer_functions:
    name: Run DataFusion producer function tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/datafusion_producer_functions.Dockerfile .)
  datafusion_consumer_functions:
    name: Run DataFusion consumer function tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/datafusion_consumer_functions.Dockerfile .)
  datafusion_producer_relations:
    name: Run DataFusion producer relation tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/datafusion_producer_relations.Dockerfile .)
  datafusion_consumer_relations:
    name: Run DataFusion consumer relation tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/datafusion_consumer_relations.Dockerfile .)
  duckdb_producer_functions:
    name: Run DuckDB producer function tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/duckdb_producer_functions.Dockerfile .)
  duckdb_consumer_functions:
    name: Run DuckDB consumer function tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/duckdb_consumer_functions.Dockerfile .)
  duckdb_producer_relations:
    name: Run DuckDB producer relation tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/duckdb_producer_relations.Dockerfile .)
  duckdb_consumer_relations:
    name: Run DuckDB consumer relation tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/duckdb_consumer_relations.Dockerfile .)
  ibis_producer:
    name: Run Ibis producer tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/ibis_producer.Dockerfile .)
  isthmus_producer_functions:
    name: Run Isthmus producer function tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/isthmus_producer_functions.Dockerfile .)
  isthmus_producer_relations:
    name: Run Isthmus producer function tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build & run
        run: docker run --rm $(docker build -q --file ./ci/docker/isthmus_producer_relations.Dockerfile .)
